version: "3"
services:
  client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    ports:
      - "1337:80"

  api:
    build:
      dockerfile: ./api/Dockerfile
      context: .
    ports:
      - "8080:8080"
